homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 21                            # Impacts weather/sunrise data (abv. sea level in meters)
  unit_system: imperial                    # metric for Metric, imperial for Imperial
  temperature_unit: F                      # C for Celcius, F for Fahrenheit
  time_zone: America/New_York              # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  customize: !include refs/customize.yaml  # Customization file
  customize_glob: !include refs/customize_glob.yaml  # Customize all entities matching a pattern
###################################################################################################
#introduction:                             # Show links to resources in log and frontend
frontend:                                  # Enables the frontend
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
    - /local/custom_ui/state-card-custom-alarm.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
http:                                      # Web frontend configuration
  api_password: !secret http_password      # This adds a password (recommended!)
  base_url: !secret http_base_url          # This is used w/ SSL/TLS
  ip_ban_enabled: True                     # Indicate if addditional IP filtering is enabled
  login_attempts_threshold: 3              # Auto-ban after number of failed attempts
  trusted_networks:                        # List of trusted networks
    - 192.168.1.0/24     
    - 192.168.5.0/24     
updater:                                   # Checks for available updates https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
  include_used_components: true            # Optional, sends HA devs system info to focus on popular components.
discovery:                                 # Discover some devices automatically
  ignore:                                  # Ignore some auto-discovery devices (list below)
    - denonavr     
recorder:                                  # Enables support for tracking state changes over time.
  purge_keep_days: 14                      # Delete events and states older than 2 weeks
config:                                    # Enables configuration UI on frontend
conversation:                              # Allows you to issue voice commands from the frontend
history:                                   # Enables tracking state changes on frontend
logbook:                                   # Enables events in a logbook on frontend
map:                                       # Enables map on frontend
sun:                                       # Track the sun
ios:                                       # Enables iOS app configuration
cloud: !include refs/cloud.yaml            # Enables connection to HA Cloud services
###################################################################################################
emulated_hue:                              # Allows alexa on/off
  host_ip: !secret alexa_host
  listen_port: !secret alexa_port
  expose_by_default: false
customizer:                                # Enables custom_ui
  custom_ui: local
  hide_attributes:
    - node_id
    - value_index
zwave:                                     # Enables zwave discovery
  usb_path: /dev/ttyACM0                   # zwave discovery via this usb device (check via ssh cmd hassio hw info)
nest:                                      # Nest auto-discovery and configuration
  client_id: !secret nest_id
  client_secret: !secret nest_secret
zone: !include refs/zones.yaml             # Geolocation zone configuration
device_tracker: !include refs/tracker.yaml # Device tracker configuration
sensor: !include refs/sensor.yaml          # Weather prediction configuration
media_player: !include refs/media.yaml     # Media player configuration
notify: !include refs/notify.yaml          # Push notifications configuration
cover: !include refs/doors.yaml            # Chamberlain MyQ Garage
camera: !include refs/camera.yaml          # Camera configuration
input_select: !include refs/inputs.yaml    # Input selection card configuration
input_boolean: !include refs/booleans.yaml # Define boolean value to enable/disable automations
switch: !include refs/cli_switch.yaml      # CLI hacks
group: !include groups.yaml                # Group (cards) and View (tabs)
script: !include scripts.yaml              # Scripts specify squences of automation operations
automation: !include automations.yaml      # Automation configuration
binary_sensor:                             # Binary sensors configuration
  - platform: ring
ring:                                      # Eanbles connetion to ring servers
  username: !secret ring_user
  password: !secret ring_pass
downloader:                                # Enables downloader for remote files (i.e. ring)
  download_dir: downloads                  # Provides download directory to store files
tts:                                       # Text to speech
  - platform: google
    cache: true
    cache_dir: tts
    time_memory: 300
weather:
  - platform: darksky
    api_key: !secret darksky_api
ffmpeg:                                    # Enables ring to download video to local dir
#usps: !include refs/usps.yaml              # USPS Informed Delivery service (broke https://github.com/home-assistant/home-assistant/issues/9143)
#    username: !secret usps_user
#    password: !secret usps_pass
#mqtt: !include refs/mqtt.yaml              # MQTT configuration
#weblink: !include refs/weblink.yaml
