title: Lovelace Demo
views:
  - title: Home
    icon: mdi:heart
    cards:
      - type: picture
        image: https://images.pexels.com/photos/220147/pexels-photo-220147.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500
        navigation_path: /lovelace/stacks
      - type: markdown
        content: >
          ## Lovelace

          Starting with Home Assistant 0.72, we're experimenting with a new way of defining your interface. We're calling it the **Lovelace UI**.

      - type: picture-glance
        image: https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=240&w=495
        title: Picture glance
        entities:
          - switch.ge_12722_onoff_relay_switch_switch
          - light.aeotec_zw111_nano_dimmer_level

      - type: weather-forecast
        entity: weather.dark_sky
      - type: media-control
        entity: media_player.kitchen
      - type: history-graph
        title: history-graph
        entities:
          - sensor.pws_temp_f
          - media_player.alices_bedroom

  - title: Stacks
    id: stacks
    cards:
      - type: vertical-stack
        cards:
          - type: media-control
            entity: media_player.alices_bedroom
          - type: picture-entity
            entity: camera.uvc1
          - type: media-control
            entity: media_player.alices_bedroom
          - type: picture-entity
            entity: camera.uvc1
      - type: horizontal-stack
        cards:
          - type: media-control
            entity: media_player.alices_bedroom
          - type: picture-entity
            entity: camera.uvc1

  - title: Entities
    cards:
      - type: entities
        entities:
          - device_tracker.thomas_iphone
          - cover.garage_door_opener
          - group.kitchen
          - light.ge_12724_3way_dimmer_switch_level_2
      - type: entities
        entities:
          - device_tracker.thomas_iphone
          - cover.garage_door_opener
          - group.kitchen
          - light.ge_12724_3way_dimmer_switch_level_2
        show_header_toggle: false
      - type: entities
        entities:
          - device_tracker.thomas_iphone
          - cover.garage_door_opener
          - group.kitchen
          - light.ge_12724_3way_dimmer_switch_level_2
        title: toggle-able
      - type: entities
        entities:
          - device_tracker.thomas_iphone
          - cover.garage_door_opener
          - group.kitchen
          - light.ge_12724_3way_dimmer_switch_level_2
        title: toggle-able, toggle = false
        show_header_toggle: false
      - type: entities
        entities:
          - device_tracker.thomas_iphone
        title: not toggle-able
      # - type: entities
      #   title: no entities

  - title: Filter
    cards:
      - type: entity-filter
        entities:
          - device_tracker.thomas_iphone
          - device_tracker.samantha_iphone
        state_filter:
          - "home"
        card:
          type: glance
          title: People at home
      - type: entity-filter
        entities:
          - light.ge_12724_3way_dimmer_switch_level_2
          - light.ge_12724_3way_dimmer_switch_level_3
        state_filter:
            - "on"
        card:
          title: domain light, state on
      - type: entity-filter
        entities:
          - light.ge_12724_3way_dimmer_switch_level_2
          - light.linear_wd500z1_wall_dimmer_switch_level
        state_filter:
          - 'on'
          - 'off'
        card:
          type: glance
          title: Filter + glance

  - title: Glance
    cards:
      - type: glance
        entities:
          - device_tracker.thomas_iphone
          - cover.garage_door_opener
          - group.kitchen
          - light.ge_12724_3way_dimmer_switch_level_2
      - type: glance
        entities:
          - device_tracker.thomas_iphone
          - cover.garage_door_opener
          - group.kitchen
          - light.ge_12724_3way_dimmer_switch_level_2
        title: Title
      - type: glance
        entities:
          - entity: device_tracker.thomas_iphone
            name: ¯\_(ツ)_/¯
          - cover.garage_door_opener
          - group.kitchen
          - light.ge_12724_3way_dimmer_switch_level_2
        title: Custom name for Thomas

  - title: Iframe
    cards:
      - type: iframe
        url: https://embed.windy.com/embed2.html?lat=48.234&lon=8.598&zoom=5&level=surface&overlay=radar&menu=&message=&marker=&calendar=&pressure=&type=map&location=coordinates&detail=&detailLat=48.234&detailLon=8.598&metricWind=default&metricTemp=default&radarRange=-12
        aspect_ratio: 50%
      - type: iframe
        url: https://embed.windy.com/embed2.html?lat=48.234&lon=8.598&zoom=5&level=surface&overlay=radar&menu=&message=&marker=&calendar=&pressure=&type=map&location=coordinates&detail=&detailLat=48.234&detailLon=8.598&metricWind=default&metricTemp=default&radarRange=-12
        aspect_ratio: 100%
        title: with title

  - title: Picture entity
    cards:
      - type: picture-entity
        entity: light.ge_12724_3way_dimmer_switch_level_2
        image: https://images.pexels.com/photos/775219/pexels-photo-775219.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=295&w=490
      - type: picture-entity
        entity: light.ge_12724_3way_dimmer_switch_level_2_xxx
        image: https://images.pexels.com/photos/775219/pexels-photo-775219.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=295&w=490
      - type: picture-entity
        entity: light.ge_12724_3way_dimmer_switch_level_2
        image: https://images.pexels.com/photos/172872/pexels-photo-172872.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260
        tap_action: toggle
        name: tap_action toggle
      - type: picture-entity
        entity: light.ge_12724_3way_dimmer_switch_level_2
        image: https://images.pexels.com/photos/775219/pexels-photo-775219.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=295&w=490
        state_image:
          "off": https://images.pexels.com/photos/172872/pexels-photo-172872.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260
        name: state_image.off only, fallback to image
      - type: picture-entity
        entity: light.ge_12724_3way_dimmer_switch_level_2
        image: https://images.pexels.com/photos/775219/pexels-photo-775219.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=295&w=490
        state_image:
          "on": https://images.pexels.com/photos/172872/pexels-photo-172872.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260
        name: state_image.on only, fallback to image
      - type: picture-entity
        entity: camera.uvc1
      - type: picture-entity
        entity: light.ge_12724_3way_dimmer_switch_level_2
        camera_image: camera.uvc1
        show_info: false

  - title: Picture elements
    cards:
      - type: picture-elements
        image: https://images.pexels.com/photos/316465/pexels-photo-316465.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260
        elements:
          - type: service-button
            title: turn light off
            style:
              top: 15%
              left: 45%
            service: light.turn_off
            service_data:
              entity_id: light.ge_12724_3way_dimmer_switch_level_2
          - type: state-badge
            entity: sensor.pws_temp_f
            style:
              top: 40%
              left: 80%
          - type: state-icon
            entity: light.ge_12724_3way_dimmer_switch_level_2
            style:
              top: 30%
              left: 55%
              '--paper-item-icon-color': green
          - type: state-icon
            tap_action: toggle
            entity: light.ge_12724_3way_dimmer_switch_level_2
            style:
              top: 30%
              left: 20%
          - type: state-label
            entity: sensor.pws_temp_f
            style:
              top: 40%
              left: 30%
          - type: navigation
            path: /lovelace/2
            icon: mdi:numeric-2-box-multiple-outline
            style:
              top: 80%
              left: 15%
              width: 48px
              height: 48px
              color: cyan
      - type: picture-elements
        title: Test overflow
        image: https://images.pexels.com/photos/316465/pexels-photo-316465.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260
        elements:
          - type: state-icon
            tap_action: toggle
            entity: light.ge_12724_3way_dimmer_switch_level_2
            style:
              top: 0
              left: 20%
  - title: panel
    id: panel
    panel: true
    cards:
      - type: picture-elements
        image: https://images.pexels.com/photos/316465/pexels-photo-316465.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260
        elements:
          - type: service-button
            title: turn light off
            style:
              top: 15%
              left: 45%
            service: light.turn_off
            service_data:
              entity_id: light.ge_12724_3way_dimmer_switch_level_2
      - type: weather-forecast
        entity: weather.dark_sky